version: '3.1'

services:
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - botnetwork
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  bot:
    build: ./bot
    container_name: bot
    ports:
      - "5000:5000"
    volumes:
      - ./bot:/usr/src/app
    environment:
      - OPENAI_API_KEY=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
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - botnetwork

  microservice:
    build: ./microservice
    container_name: micro_whatsapp
    ports:
      - "8000:8000"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ./microservice:/usr/src/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - botnetwork
    shm_size: 2gb
    
volumes:
  node_modules:

networks:
  botnetwork:
    driver: bridge
